"""Queries: the requests a query sends, and how answers decode. Built into ../queries.json by build.py."""
import json


def page(items, cursor=None, **extra): return {"status": 200, "body": {"items": items, "next_cursor": cursor, "stats": {}, **extra}}
def get(path, **query): return {"method": "GET", "path": path, "query": query, "keyed": False}
q = lambda resource, steps, run: {"query": resource, "steps": steps, "run": run}
value = 'Japanese "quotes" \\ slash\n猫'
cases = [
 {"name": "take sends one bounded GET with the selection, filters and search",
  "call": q("cards", [["search", "is:due"], ["where", "interval", "gte", 30], ["select", "id", "question"]], ["take", 20]),
  "exchanges": [{"request": get("/v1/cards", select="id,question", shape="object", where=["interval>=30"], search="is:due", limit="20"),
                 "response": page([{"id": 1, "question": "<b>食べる</b>"}])}],
  "result": [{"id": 1, "question": "<b>食べる</b>"}]},
 {"name": "filters, sorts and distinct use wire names and codes; rows come back in client names and values",
  "call": q("cards", [["where", "queue", "in", ["siblingBuried", "manuallyBuried"]], ["where", "flag", "ne", "none"],
                      ["where", "originalPosition", "eq", None], ["where", "deckName", "startsWith", "日本::"],
                      ["where", "deckName", "notIn", ["a", "b"]], ["orderBy", "easeFactor", "desc"], ["distinctOn", "noteId"],
                      ["select", "id", "queue", "flag", "originalPosition", "memoryState"]], ["take", 5]),
  "exchanges": [{"request": get("/v1/cards", select="id,queue,flag,original_position,memory_state", shape="object",
                                where=["queue in[-2,-3]", "flag!=0", "original_position==null", 'deck_name^="日本::"', 'deck_name not in["a","b"]'],
                                order="ease:desc", distinct_on="note_id", limit="5"),
                 "response": page([{"id": 1, "queue": -2, "flag": 3, "original_position": None, "memory_state": {"stability": 2.5, "difficulty": 5}}])}],
  "result": [{"id": 1, "queue": "siblingBuried", "flag": "green", "originalPosition": None, "memoryState": {"stability": 2.5, "difficulty": 5}}]},
 {"name": "text values are sent as JSON strings, each filter its own where",
  "call": q("cards", [["select", "id"], ["where", "deckName", "eq", value], ["where", "interval", "gt", 1], ["where", "suspended", "eq", True]], ["take", 1]),
  "exchanges": [{"request": get("/v1/cards", select="id", shape="object", where=["deck_name==" + json.dumps(value, ensure_ascii=False), "interval>1", "suspended==true"], limit="1"),
                 "response": page([{"id": 1}])}],
  "result": [{"id": 1}]},
 {"name": "contains and endsWith on free text",
  "call": q("notes", [["where", "firstField", "contains", "a"], ["where", "firstField", "endsWith", "ot"], ["select", "firstField"]], ["take", 10]),
  "exchanges": [{"request": get("/v1/notes", select="first_field", shape="object", where=['first_field~="a"', 'first_field$="ot"'], limit="10"),
                 "response": page([{"first_field": "carrot"}])}],
  "result": [{"firstField": "carrot"}]},
 {"name": "a review's rating 0 reads and filters as null",
  "call": q("reviews", [["where", "rating", "eq", None], ["where", "type", "notIn", ["manual", "rescheduled"]], ["select", "rating", "type"]], ["take", 2]),
  "exchanges": [{"request": get("/v1/reviews", select="ease,type", shape="object", where=["ease==0", "type not in[4,5]"], limit="2"),
                 "response": page([{"ease": 0, "type": 4}, {"ease": 3, "type": 1}])}],
  "result": [{"rating": None, "type": "manual"}, {"rating": "good", "type": "review"}]},
 {"name": "nested rows use client names: a note field's ord is index",
  "call": q("notes", [["select", "fields"]], ["take", 1]),
  "exchanges": [{"request": get("/v1/notes", select="fields", shape="object", limit="1"),
                 "response": page([{"fields": [{"name": "Front", "value": "犬", "ord": 0}]}])}],
  "result": [{"fields": [{"name": "Front", "value": "犬", "index": 0}]}]},
 {"name": "a template's ord is index and its did is deckId",
  "call": q("noteTypes", [["select", "templates"]], ["take", 1]),
  "exchanges": [{"request": get("/v1/models", select="templates", shape="object", limit="1"),
                 "response": page([{"templates": [{"name": "Card 1", "ord": 0, "qfmt": "{{Front}}", "afmt": "", "bqfmt": "", "bafmt": "", "did": None}]}])}],
  "result": [{"templates": [{"name": "Card 1", "index": 0, "qfmt": "{{Front}}", "afmt": "", "bqfmt": "", "bafmt": "", "deckId": None}]}]},
 {"name": "without select there is no select parameter and rows have every field",
  "call": q("tags", [], ["take", 1]),
  "exchanges": [{"request": get("/v1/tags", shape="object", limit="1"), "response": page([{"name": "a::b"}])}],
  "result": [{"name": "a::b"}]},
 {"name": "values reads bare values with shape=scalar",
  "call": q("cards", [["values", "id"]], ["take", 3]),
  "exchanges": [{"request": get("/v1/cards", select="id", shape="scalar", limit="3"), "response": page([1, 2, 3])}],
  "result": [1, 2, 3]},
 {"name": "values on a named field returns names",
  "call": q("cards", [["values", "flag"]], ["take", 2]),
  "exchanges": [{"request": get("/v1/cards", select="flag", shape="scalar", limit="2"), "response": page([0, 4])}],
  "result": ["none", "blue"]},
 {"name": "count asks for the total with limit 0",
  "call": q("notes", [["search", "tag:verb"]], ["count"]),
  "exchanges": [{"request": get("/v1/notes", shape="object", search="tag:verb", include="total", limit="0"), "response": page([], total=12)}],
  "result": 12},
 {"name": "a page can carry the total",
  "call": q("notes", [["select", "id"]], ["page", {"size": 10, "total": True}]),
  "exchanges": [{"request": get("/v1/notes", select="id", shape="object", include="total", limit="10"), "response": page([{"id": 1}], total=12)}],
  "result": {"items": [{"id": 1}], "hasMore": False, "total": 12}},
 {"name": "a page without total says null",
  "call": q("notes", [["select", "id"]], ["page", {}]),
  "exchanges": [{"request": get("/v1/notes", select="id", shape="object", limit="50"), "response": page([{"id": 1}])}],
  "result": {"items": [{"id": 1}], "hasMore": False, "total": None}},
 {"name": "the next page repeats the query with the cursor",
  "call": q("cards", [["search", "is:due"], ["select", "id"]], ["pages", {"size": 1}]),
  "exchanges": [
    {"request": get("/v1/cards", select="id", shape="object", search="is:due", limit="1"), "response": page([{"id": 1}], "opaque +/=")},
    {"request": get("/v1/cards", select="id", shape="object", search="is:due", limit="1", cursor="opaque +/="), "response": page([{"id": 2}])}],
  "result": [{"id": 1}, {"id": 2}]},
 {"name": "a long query is sent as POST /query with the same names, and no key",
  "client": {"maxGetUrlLength": 80},
  "call": q("cards", [["search", "tag:" + "長" * 100], ["values", "id"]], ["take", 1]),
  "exchanges": [{"request": {"method": "POST", "path": "/v1/cards/query", "query": {}, "keyed": False,
                             "body": {"select": "id", "where": [], "shape": "scalar", "search": "tag:" + "長" * 100, "limit": 1}},
                 "response": page([12])}],
  "result": [12]},
 {"name": "take(0) sends nothing", "call": q("cards", [], ["take", 0]), "exchanges": [], "result": []},
 {"name": "is adds Anki states to the search, after the text, all of which must hold",
  "call": q("cards", [["search", "deck:Mining OR deck:Kaishi"], ["is", "suspended"], ["is", "due"], ["select", "id"]], ["take", 5]),
  "exchanges": [{"request": get("/v1/cards", select="id", shape="object", search="(deck:Mining OR deck:Kaishi) is:suspended is:due", limit="5"),
                 "response": page([{"id": 1}])}],
  "result": [{"id": 1}]},
 {"name": "is without a search sends the terms alone, in Anki's words, each once",
  "call": q("notes", [["is", "siblingBuried"], ["is", "learning"], ["is", "siblingBuried"], ["select", "id"]], ["take", 1]),
  "exchanges": [{"request": get("/v1/notes", select="id", shape="object", search="is:buried-sibling is:learn", limit="1"),
                 "response": page([{"id": 7}])}],
  "result": [{"id": 7}]},
 {"name": "a later search replaces the text and keeps the states; count sends them too",
  "call": q("reviews", [["search", "deck:A"], ["is", "manuallyBuried"], ["search", "deck:B"]], ["count"]),
  "exchanges": [{"request": get("/v1/reviews", shape="object", search="(deck:B) is:buried-manually", include="total", limit="0"),
                 "response": page([], total=3)}],
  "result": 3},
]
refused = [
 ("an unknown field", "cards", [["select", "questoin"]]),
 ("a wire name instead of the client's", "cards", [["select", "note_id"]]),
 ("a string for a number", "cards", [["where", "interval", "gte", "30"]]),
 ("null on a field that can't be null", "cards", [["where", "interval", "eq", None]]),
 ("a code instead of a value name", "cards", [["where", "queue", "eq", -1]]),
 ("a value name the field doesn't list", "cards", [["where", "queue", "eq", "buried"]]),
 ("an order comparison on a named value", "cards", [["where", "flag", "gt", "red"]]),
 ("a text operator on a number", "cards", [["where", "interval", "contains", 30]]),
 ("in without a list", "cards", [["where", "queue", "in", "new"]]),
 ("a list with eq", "cards", [["where", "interval", "eq", [1]]]),
 ("an unknown operator", "cards", [["where", "deckName", "like", "x"]]),
 ("values on a list field", "notes", [["values", "tags"]]),
 ("distinctOn on a list field", "notes", [["distinctOn", "fields"]]),
 ("an unknown sort", "cards", [["orderBy", "question"]]),
 ("select with no fields", "cards", [["select"]]),
 ("a state Anki doesn't have", "cards", [["is", "sleeping"]]),
 ("Anki's term instead of the client's name", "cards", [["is", "learn"]]),
 ("is on a list that takes no search", "decks", [["is", "suspended"]]),
]
for name, resource, steps in refused:
    cases.append({"name": f"refused before sending: {name}", "call": q(resource, steps, ["take", 1]), "exchanges": [], "error": {"kind": "argument"}})
cases.append({"name": "refused before sending: a negative take", "call": q("cards", [], ["take", -1]), "exchanges": [], "error": {"kind": "argument"}})
for name, row in [("a string id", {"id": "1", "question": "q"}), ("a missing selected field", {"id": 1}),
                  ("null where none is allowed", {"id": 1, "question": None})]:
    cases.append({"name": f"a protocol error: {name}", "call": q("cards", [["select", "id", "question"]], ["take", 1]),
                  "exchanges": [{"request": get("/v1/cards", select="id,question", shape="object", limit="1"), "response": page([row])}],
                  "error": {"kind": "protocol"}})
cases += [
 {"name": "a protocol error: a code the description doesn't list", "call": q("cards", [["select", "queue"]], ["take", 1]),
  "exchanges": [{"request": get("/v1/cards", select="queue", shape="object", limit="1"), "response": page([{"queue": 9}])}],
  "error": {"kind": "protocol"}},
 {"name": "a protocol error: more rows than the limit", "call": q("cards", [["values", "id"]], ["take", 1]),
  "exchanges": [{"request": get("/v1/cards", select="id", shape="scalar", limit="1"), "response": page([1, 2])}],
  "error": {"kind": "protocol"}},
 {"name": "a protocol error: a cursor given twice", "call": q("cards", [["values", "id"]], ["pages", {"size": 1}]),
  "exchanges": [{"request": get("/v1/cards", select="id", shape="scalar", limit="1"), "response": page([1], "same")},
                {"request": get("/v1/cards", select="id", shape="scalar", limit="1", cursor="same"), "response": page([2], "same")}],
  "error": {"kind": "protocol"}},
]
