"""Watching a query, as scripted scenarios. Built into ../watch.json by build.py."""
def events(resources): return {"method": "GET", "path": "/v1/events", "query": {"resources": ",".join(sorted(resources)), "types": "change"}}
def ready(resources): return {"send": [{"event": "ready", "data": {"type": "ready", "session_id": "s", "after_seq": 0, "ts": 1, "resources": sorted(resources), "heartbeat_ms": 15000}}]}
def page(items, cursor=None): return {"status": 200, "body": {"items": items, "next_cursor": cursor, "stats": {}}}
def msg(type_, ids=None, origin=None, client=None, **extra):
    data = {"type": type_, "seq": 1, "session_id": "s", "ts": 1, **({"ids": ids} if ids is not None else {}), **({"origin": origin} if origin else {}), **({"client": client} if client else {}), **extra}
    return {"event": type_, "data": data}
def send(*messages): return {"send": list(messages)}
ALL = ["cards", "decks", "models", "notes", "tags"]
# A notes watch on a search, selecting firstField: the id is added to the select.
def nread(where=(), search="deck:Mining", cursor=None):
    q = {"select": "first_field,id", "shape": "object", "limit": "2000"}
    if where: q["where"] = list(where)
    if search: q["search"] = search
    if cursor: q["cursor"] = cursor
    return {"method": "GET", "path": "/v1/notes", "query": q, "keyed": False}
def row(i, text): return {"first_field": text, "id": i}
def crow(i, text): return {"firstField": text, "id": i}
first = {"initial": True, "by": None, "app": None}
unk = {"initial": False, "by": None, "app": None}
ui = {"initial": False, "by": "ui", "app": None}
api = {"initial": False, "by": "api", "app": "Yomitan"}
mining = {"query": "notes", "steps": [["search", "deck:Mining"], ["select", "firstField"]], "method": "watch"}
def start(rows=((1, "apple"), (2, "banana"))):
    return [{"call": mining, "as": "w", "listener": "h"},
            {"expect": events(ALL), "stream": True}, ready(ALL),
            {"expect": nread(), "response": page([row(i, t) for i, t in rows])},
            {"settle": "w", "ok": True},
            {"heard": "h", "calls": [["added", [crow(i, t) for i, t in rows], first]]}]
cases = [
 {"name": "the first load waits for the connection, reads the query, and comes as added with initial",
  "script": start()},
 {"name": "the first load reads every page, 2,000 rows each, and delivers them together",
  "script": [{"call": mining, "as": "w", "listener": "h"}, {"expect": events(ALL), "stream": True}, ready(ALL),
             {"expect": nread(), "response": page([row(1, "apple")], "c1")},
             {"expect": nread(cursor="c1"), "response": page([row(2, "banana")])},
             {"settle": "w", "ok": True}, {"heard": "h", "calls": [["added", [crow(1, "apple"), crow(2, "banana")], first]]}]},
 {"name": "created ids are checked against the query: matching rows come as added, with who made them",
  "script": start() + [send(msg("notes.created", [3, 4], "api", "Yomitan")),
                       {"expect": nread(search="(deck:Mining) nid:3,4"), "response": page([row(3, "carrot")])},
                       {"heard": "h", "calls": [["added", [crow(3, "carrot")], api]]}]},
 {"name": "updated ids: a changed row is updated, an unchanged one is nothing, one that no longer matches is removed",
  "script": start() + [send(msg("notes.updated", [1, 2], "ui")),
                       {"expect": nread(search="(deck:Mining) nid:1,2"), "response": page([row(2, "banana")])},
                       {"heard": "h", "calls": [["removed", [1], ui]]},
                       send(msg("notes.updated", [2], "ui")),
                       {"expect": nread(search="(deck:Mining) nid:2"), "response": page([row(2, "Banana")])},
                       {"heard": "h", "calls": [["updated", [crow(2, "Banana")], ui]]}]},
 {"name": "an update that makes a row match comes as added",
  "script": start() + [send(msg("notes.updated", [9], "ui")),
                       {"expect": nread(search="(deck:Mining) nid:9"), "response": page([row(9, "date")])},
                       {"heard": "h", "calls": [["added", [crow(9, "date")], ui]]}]},
 {"name": "deleted ids come as removed without a request, only for rows seen",
  "script": start() + [send(msg("notes.deleted", [2, 7], "api", "Yomitan")), {"quiet": True},
                       {"heard": "h", "calls": [["removed", [2], api]]}]},
 {"name": "stale: everything is read again and only the differences are delivered",
  "script": start() + [send(msg("notes.stale", reason="details_unavailable")),
                       {"expect": nread(), "response": page([row(1, "Apple"), row(3, "carrot")])},
                       {"heard": "h", "calls": [["removed", [2], unk], ["updated", [crow(1, "Apple")], unk], ["added", [crow(3, "carrot")], unk]]}]},
 {"name": "a related resource's stale reads everything again (a deck rename changes deck: matches)",
  "script": start() + [send(msg("decks.stale", reason="details_unavailable")),
                       {"expect": nread(), "response": page([row(1, "apple")])},
                       {"heard": "h", "calls": [["removed", [2], unk]]}]},
 {"name": "a gap reads everything again",
  "script": start() + [send({"event": "gap", "data": {"type": "gap", "after_seq": 0, "session_id": "s", "ts": 1, "reason": "lagged", "discarded": 4}}),
                       {"expect": nread(), "response": page([row(1, "apple"), row(2, "banana")])}, {"heard": "h", "calls": []}]},
 {"name": "after a drop, the new ready reads everything again",
  "script": start() + [{"end": True}, {"wait": 1000}, {"expect": events(ALL), "stream": True}, ready(ALL),
                       {"expect": nread(), "response": page([row(1, "apple")])}, {"heard": "h", "calls": [["removed", [2], unk]]}]},
 {"name": "card ids on a notes watch: their notes are found, then checked",
  "script": start() + [send(msg("cards.updated", [11, 12], "ui")),
                       {"expect": {"method": "GET", "path": "/v1/notes", "query": {"select": "id", "shape": "scalar", "search": "cid:11,12", "limit": "2000"}},
                        "response": page([1])},
                       {"expect": nread(search="(deck:Mining) nid:1"), "response": page([])},
                       {"heard": "h", "calls": [["removed", [1], ui]]}]},
 {"name": "messages that arrive during a read are held and checked after it",
  "script": [{"call": mining, "as": "w", "listener": "h"}, {"expect": events(ALL), "stream": True}, ready(ALL),
             send(msg("notes.created", [3], "ui")),
             {"expect": nread(), "response": page([row(1, "apple")])},
             {"settle": "w", "ok": True},
             {"expect": nread(search="(deck:Mining) nid:3"), "response": page([row(3, "carrot")])},
             {"heard": "h", "calls": [["added", [crow(1, "apple")], first], ["added", [crow(3, "carrot")], ui]]}]},
 {"name": "messages that arrive during a check become one check; a delete wins over an update",
  "script": start() + [send(msg("notes.updated", [1], "ui")),
                       send(msg("notes.updated", [5], "ui"), msg("notes.updated", [2], "ui"), msg("notes.deleted", [2], "ui")),
                       {"expect": nread(search="(deck:Mining) nid:1"), "response": page([row(1, "apple")])},
                       {"expect": nread(search="(deck:Mining) nid:5"), "response": page([row(5, "egg")])},
                       {"heard": "h", "calls": [["removed", [2], ui], ["added", [crow(5, "egg")], ui]]}]},
 {"name": "a failed check is retried by reading everything again after 1 s",
  "script": start() + [send(msg("notes.created", [3], "ui")),
                       {"expect": nread(search="(deck:Mining) nid:3"), "response": {"status": 503, "body": {"detail": "busy"}}},
                       {"wait": 999}, {"quiet": True}, {"wait": 1},
                       {"expect": nread(), "response": page([row(1, "apple"), row(2, "banana"), row(3, "carrot")])},
                       {"heard": "h", "calls": [["added", [crow(3, "carrot")], unk]]}]},
 {"name": "a 403 ends the watch: the error handler hears it",
  "script": start() + [send(msg("notes.created", [3], "ui")),
                       {"expect": nread(search="(deck:Mining) nid:3"), "response": {"status": 403, "body": {"detail": "no"}}},
                       {"heard": "h", "calls": [["error", "permission"]]}, {"settle": "w", "done": True, "result": None}]},
 {"name": "the first load failing fails the watch",
  "script": [{"call": mining, "as": "w", "listener": "h"}, {"expect": events(ALL), "stream": True}, ready(ALL),
             {"expect": nread(), "response": {"status": 503, "body": {"detail": "busy"}}},
             {"settle": "w", "error": {"kind": "http", "status": 503}}]},
 {"name": "a connection that can't be made at first fails the watch instead of waiting",
  "script": [{"call": mining, "as": "w", "listener": "h"}, {"expect": events(ALL), "response": {"status": 503, "body": {"detail": "No active event session"}}},
             {"settle": "w", "error": {"kind": "http", "status": 503}}, {"wait": 60000}, {"quiet": True}]},
 {"name": "a stream that won't carry the watch's resource fails it with a permission error",
  "script": [{"call": mining, "as": "w", "listener": "h"}, {"expect": events(ALL), "stream": True}, ready(["decks"]),
             {"settle": "w", "error": {"kind": "permission"}}]},
 {"name": "without a search, a notes watch listens to notes alone",
  "script": [{"call": {"query": "notes", "steps": [["select", "firstField"]], "method": "watch"}, "as": "w", "listener": "h"},
             {"expect": events(["notes"]), "stream": True}, ready(["notes"]),
             {"expect": nread(search=None), "response": page([row(1, "apple")])}, {"settle": "w", "ok": True}]},
 {"name": "a cards watch selecting fields also listens to notes and note types (the fields' x-from); note ids find their cards",
  "script": [{"call": {"query": "cards", "steps": [["select", "fields"]], "method": "watch"}, "as": "w", "listener": "h"},
             {"expect": events(["cards", "models", "notes"]), "stream": True}, ready(["cards", "models", "notes"]),
             {"expect": {"method": "GET", "path": "/v1/cards", "query": {"select": "fields,id", "shape": "object", "limit": "2000"}},
              "response": page([{"fields": [{"name": "Front", "value": "a", "ord": 0}], "id": 11}])},
             {"settle": "w", "ok": True},
             {"heard": "h", "calls": [["added", [{"fields": [{"name": "Front", "value": "a", "index": 0}], "id": 11}], first]]},
             send(msg("notes.updated", [1], "ui")),
             {"expect": {"method": "GET", "path": "/v1/cards", "query": {"select": "id", "shape": "scalar", "where": ["note_id in[1]"], "limit": "2000"}}, "response": page([11])},
             {"expect": {"method": "GET", "path": "/v1/cards", "query": {"select": "fields,id", "shape": "object", "where": ["id in[11]"], "limit": "2000"}},
              "response": page([{"fields": [{"name": "Front", "value": "A", "ord": 0}], "id": 11}])},
             {"heard": "h", "calls": [["updated", [{"fields": [{"name": "Front", "value": "A", "index": 0}], "id": 11}], ui]]}]},
 {"name": "a decks watch checks the decks named in decks.counts",
  "script": [{"call": {"query": "decks", "steps": [["select", "name", "reviewCount"]], "method": "watch"}, "as": "w", "listener": "h"},
             {"expect": events(["decks"]), "stream": True}, ready(["decks"]),
             {"expect": {"method": "GET", "path": "/v1/decks", "query": {"select": "name,review_count,id", "shape": "object", "limit": "2000"}},
              "response": page([{"name": "Default", "review_count": 4, "id": 1}])},
             {"settle": "w", "ok": True},
             send(msg("decks.counts", decks=[{"id": 1, "new_count": 0, "learn_count": 0, "review_count": 3, "total_in_deck": 9}])),
             {"expect": {"method": "GET", "path": "/v1/decks", "query": {"select": "name,review_count,id", "shape": "object", "where": ["id in[1]"], "limit": "2000"}},
              "response": page([{"name": "Default", "review_count": 3, "id": 1}])},
             {"heard": "h", "calls": [["added", [{"name": "Default", "reviewCount": 4, "id": 1}], first], ["updated", [{"name": "Default", "reviewCount": 3, "id": 1}], unk]]}]},
 {"name": "a tags watch is keyed by name and kept by reading again",
  "script": [{"call": {"query": "tags", "steps": [], "method": "watch"}, "as": "w", "listener": "h"},
             {"expect": events(["tags"]), "stream": True}, ready(["tags"]),
             {"expect": {"method": "GET", "path": "/v1/tags", "query": {"shape": "object", "limit": "2000"}}, "response": page([{"name": "verb"}, {"name": "noun"}])},
             {"settle": "w", "ok": True}, send(msg("tags.stale", reason="details_unavailable")),
             {"expect": {"method": "GET", "path": "/v1/tags", "query": {"shape": "object", "limit": "2000"}}, "response": page([{"name": "verb"}, {"name": "adj"}])},
             {"heard": "h", "calls": [["added", [{"name": "verb"}, {"name": "noun"}], first], ["removed", ["noun"], unk], ["added", [{"name": "adj"}], unk]]}]},
 {"name": "a second watch needing more reconnects the shared connection; both read again",
  "script": [{"call": {"query": "notes", "steps": [["select", "firstField"]], "method": "watch"}, "as": "a", "listener": "ha"},
             {"expect": events(["notes"]), "stream": True}, ready(["notes"]),
             {"expect": nread(search=None), "response": page([row(1, "apple")])}, {"settle": "a", "ok": True},
             {"call": {"query": "cards", "steps": [["select", "due"]], "method": "watch"}, "as": "b", "listener": "hb"},
             {"expect": events(["cards", "notes"]), "stream": True}, ready(["cards", "notes"]),
             {"expect": nread(search=None), "response": page([row(1, "apple")])},
             {"expect": {"method": "GET", "path": "/v1/cards", "query": {"select": "due,id", "shape": "object", "limit": "2000"}}, "response": page([{"due": 3, "id": 11}])},
             {"settle": "b", "ok": True},
             {"heard": "ha", "calls": [["added", [crow(1, "apple")], first]]},
             {"heard": "hb", "calls": [["added", [{"due": 3, "id": 11}], first]]}]},
 {"name": "a second watch the connection already carries starts at once",
  "script": [{"call": {"query": "notes", "steps": [["select", "firstField"]], "method": "watch"}, "as": "a", "listener": "ha"},
             {"expect": events(["notes"]), "stream": True}, ready(["notes"]),
             {"expect": nread(search=None), "response": page([row(1, "apple")])}, {"settle": "a", "ok": True},
             {"call": {"query": "notes", "steps": [["select", "firstField"], ["where", "firstField", "startsWith", "a"]], "method": "watch"}, "as": "b", "listener": "hb"},
             {"expect": {"method": "GET", "path": "/v1/notes", "query": {"select": "first_field,id", "shape": "object", "where": ['first_field^="a"'], "limit": "2000"}}, "response": page([row(1, "apple")])},
             {"settle": "b", "ok": True}]},
 {"name": "on a shared connection, a watch ignores messages about resources it doesn't follow",
  "script": [{"call": {"query": "notes", "steps": [["select", "firstField"]], "method": "watch"}, "as": "a", "listener": "ha"},
             {"expect": events(["notes"]), "stream": True}, ready(["notes"]),
             {"expect": nread(search=None), "response": page([row(1, "apple")])}, {"settle": "a", "ok": True},
             {"call": {"method": "decks.onCounts"}, "as": "b", "listener": "hb"},
             {"expect": events(["decks", "notes"]), "stream": True}, ready(["decks", "notes"]),
             {"expect": nread(search=None), "response": page([row(1, "apple")])}, {"settle": "b", "ok": True},
             send(msg("decks.stale", reason="details_unavailable")), {"quiet": True},
             {"heard": "ha", "calls": [["added", [crow(1, "apple")], first]]}]},
 {"name": "stop() leaves: with nothing else listening, the connection closes and nothing more is read",
  "script": start() + [{"stop": "w"}, {"settle": "w", "done": True, "result": None}, {"wait": 60000}, {"quiet": True}, {"heard": "h", "calls": []}]},
]
