"""Writes: request bodies, keys, per-item results, errors, sync. Built into ../writes.json by build.py."""
ok = lambda body, status=200: {"status": status, "body": body}
def post(path, body, keyed=True, query=None): return {"method": "POST", "path": path, "query": query or {}, **({} if body is None else {"body": body}), "keyed": keyed}
note = {"deck": "Japanese", "noteType": "Basic", "fields": {"Front": "食べる", "Back": "to eat"}}
wire = {"deck_name": "Japanese", "model_name": "Basic", "fields": {"Front": "食べる", "Back": "to eat"}}
m = lambda method, *args: {"method": method, "args": list(args)}
cases = [
 {"name": "create sends a list of one, keyed, and returns the receipt without reading the note",
  "call": m("notes.create", note),
  "exchanges": [{"request": post("/v1/notes", [wire]), "response": ok({"created": [{"index": 0, "id": 42}], "failed": []})}],
  "result": {"index": 0, "id": 42, "cards": None, "files": None}},
 {"name": "a note by ids, with tags",
  "call": m("notes.create", {**note, "deck": {"id": 3}, "noteType": {"id": 4}, "tags": ["mined"]}),
  "exchanges": [{"request": post("/v1/notes", [{"deck_id": 3, "model_id": 4, "fields": wire["fields"], "tags": ["mined"]}]),
                 "response": ok({"created": [{"index": 0, "id": 42}], "failed": []})}],
  "result": {"index": 0, "id": 42, "cards": None, "files": None}},
 {"name": "files, duplicate options and includes; per-item results in input order",
  "call": m("notes.createMany", [
      {**note, "tags": ["mined"], "duplicates": {"scope": "deck", "deck": "Japanese", "includeSubdecks": True, "allNoteTypes": True},
       "audio": [{"data": {"$bytes": "aGkh"}, "filename": "inu.mp3", "fields": ["Back"]}], "picture": [{"url": "https://example.com/inu.png"}],
       "video": [{"path": "C:/clips/inu.mp4"}]},
      {**note, "duplicates": {"allow": True}}],
      {"onError": "collect", "cards": True, "duplicateIds": True}),
  "exchanges": [{"request": post("/v1/notes", [
      {**wire, "tags": ["mined"], "duplicate_scope": "deck",
       "duplicate_scope_options": {"deck_name": "Japanese", "check_children": True, "check_all_models": True},
       "audio": [{"data": "aGkh", "filename": "inu.mp3", "fields": ["Back"]}], "picture": [{"url": "https://example.com/inu.png"}],
       "video": [{"path": "C:/clips/inu.mp4"}]},
      {**wire, "allow_duplicate": True}], query={"include": "cards,duplicate_ids"}),
     "response": ok({"created": [{"index": 1, "id": 11, "cards": [21], "files": [{"filename": "inu-1.mp3", "requested_filename": "inu.mp3", "renamed": True, "size": 3}]}],
                     "failed": [{"index": 0, "code": "duplicate", "message": "dup", "duplicate_note_ids": [5]}]})}],
  "result": {"items": [
      {"ok": False, "index": 0, "error": {"index": 0, "code": "duplicate", "message": "dup", "duplicateNoteIds": [5], "attachment": None}},
      {"ok": True, "index": 1, "value": {"index": 1, "id": 11, "cards": [21], "files": [{"filename": "inu-1.mp3", "requestedFilename": "inu.mp3", "renamed": True, "size": 3}]}}]}},
 {"name": "a failed item of a single create is an item error",
  "call": m("notes.create", note),
  "exchanges": [{"request": post("/v1/notes", [wire]), "response": ok({"created": [], "failed": [{"index": 0, "code": "duplicate", "message": "dup"}]})}],
  "error": {"kind": "itemRejected"}},
 {"name": "a batch with a failed item is a partial write",
  "call": m("notes.createMany", [note, note]),
  "exchanges": [{"request": post("/v1/notes", [wire, wire]),
                 "response": ok({"created": [{"index": 1, "id": 2}], "failed": [{"index": 0, "code": "invalid_note", "message": "empty"}]})}],
  "error": {"kind": "partialWrite"}},
 {"name": "a batch that all succeeds returns the values in input order",
  "call": m("notes.createMany", [note, note]),
  "exchanges": [{"request": post("/v1/notes", [wire, wire]), "response": ok({"created": [{"index": 1, "id": 2}, {"index": 0, "id": 1}], "failed": []})}],
  "result": [{"index": 0, "id": 1, "cards": None, "files": None}, {"index": 1, "id": 2, "cards": None, "files": None}]},
 {"name": "an empty batch sends nothing", "call": m("notes.createMany", []), "exchanges": [], "result": []},
 {"name": "a file needs exactly one of data, url or path", "call": m("notes.create", {**note, "audio": [{"url": "u", "path": "p"}]}),
  "exchanges": [], "error": {"kind": "argument"}},
 {"name": "a receipt with an index missing leaves the outcome unknown, with the key",
  "call": m("notes.create", note, {"idempotencyKey": "saved-edit"}),
  "exchanges": [{"request": post("/v1/notes", [wire], keyed="saved-edit"), "response": ok({"created": [], "failed": []})}],
  "error": {"kind": "outcomeUnknown", "idempotencyKey": "saved-edit"}},
 {"name": "a failure code the description doesn't list leaves the outcome unknown",
  "call": m("notes.create", note, {"idempotencyKey": "k"}),
  "exchanges": [{"request": post("/v1/notes", [wire], keyed="k"), "response": ok({"created": [], "failed": [{"index": 0, "code": "exploded", "message": "?"}]})}],
  "error": {"kind": "outcomeUnknown", "idempotencyKey": "k"}},
 {"name": "a 503 to a write leaves the outcome unknown; no retry",
  "call": m("notes.create", note, {"idempotencyKey": "edit-1"}),
  "exchanges": [{"request": post("/v1/notes", [wire], keyed="edit-1"), "response": ok({"detail": "busy", "reason": "busy"}, 503)}],
  "error": {"kind": "outcomeUnknown", "idempotencyKey": "edit-1"}},
 {"name": "a 409 is an HTTP error with its status and detail",
  "call": m("notes.create", note),
  "exchanges": [{"request": post("/v1/notes", [wire]), "response": ok({"detail": "private field"}, 409)}],
  "error": {"kind": "http", "status": 409, "detail": "private field"}},
 {"name": "a 401 is an authentication error",
  "call": m("notes.create", note),
  "exchanges": [{"request": post("/v1/notes", [wire]), "response": ok({"detail": "Access denied"}, 401)}],
  "error": {"kind": "authentication", "status": 401}},
 {"name": "a 403 is a permission error",
  "call": m("notes.update", 1, {"fields": {"Front": "a"}}),
  "exchanges": [{"request": {"method": "PATCH", "path": "/v1/notes/1", "query": {}, "body": {"fields": {"Front": "a"}}, "keyed": True},
                 "response": ok({"detail": "no write:notes"}, 403)}],
  "error": {"kind": "permission", "status": 403, "detail": "no write:notes"}},
 {"name": "an update sends only what is given and returns nothing",
  "call": m("notes.update", 42, {"fields": {"Back": ""}, "addTags": ["new"], "removeTags": ["old"], "noteType": "Cloze",
                                  "picture": [{"url": "https://example.com/a.png", "fields": ["Back"]}]}),
  "exchanges": [{"request": {"method": "PATCH", "path": "/v1/notes/42", "query": {}, "keyed": True,
                             "body": {"fields": {"Back": ""}, "add_tags": ["new"], "remove_tags": ["old"], "model_name": "Cloze",
                                      "picture": [{"url": "https://example.com/a.png", "fields": ["Back"]}]}},
                 "response": ok({"result": {"id": 42}, "stats": {}})}],
  "result": None},
 {"name": "exists is a read of the check: no key; a duplicate is saved",
  "call": m("notes.exists", note),
  "exchanges": [{"request": post("/v1/notes:check", {"notes": [wire]}, keyed=False),
                 "response": ok({"results": [{"index": 0, "can_add": False, "state": "duplicate", "reason": "duplicate", "duplicate_note_ids": None}], "stats": {}})}],
  "result": True},
 {"name": "exists on a list answers each note in order; only a duplicate is saved",
  "call": m("notes.exists", [note, {**note, "fields": {"Front": "猫"}}, {**note, "fields": {"Front": ""}}]),
  "exchanges": [{"request": post("/v1/notes:check", {"notes": [wire, {**wire, "fields": {"Front": "猫"}}, {**wire, "fields": {"Front": ""}}]}, keyed=False),
                 "response": ok({"results": [
                     {"index": 0, "can_add": False, "state": "duplicate", "reason": "duplicate", "duplicate_note_ids": None},
                     {"index": 1, "can_add": True, "state": "normal", "reason": None, "duplicate_note_ids": None},
                     {"index": 2, "can_add": False, "state": "empty", "reason": "empty", "duplicate_note_ids": None}], "stats": {}})}],
  "result": [True, False, False]},
 {"name": "exists raises an item error for a note naming what doesn't exist",
  "call": m("notes.exists", {**note, "deck": "Nope"}),
  "exchanges": [{"request": post("/v1/notes:check", {"notes": [{**wire, "deck_name": "Nope"}]}, keyed=False),
                 "response": ok({"results": [{"index": 0, "can_add": False, "state": "invalid", "reason": "Unknown deck 'Nope'", "duplicate_note_ids": None}], "stats": {}})}],
  "error": {"kind": "itemRejected", "failure": {"index": 0, "code": "invalid", "message": "Unknown deck 'Nope'"}}},
 {"name": "exists with an empty list sends nothing", "call": m("notes.exists", []), "exchanges": [], "result": []},
 {"name": "check is a read: no key; states in client names",
  "call": m("notes.check", [note], {"duplicateIds": True}),
  "exchanges": [{"request": post("/v1/notes:check", {"notes": [wire]}, keyed=False, query={"include": "duplicate_ids"}),
                 "response": ok({"results": [{"index": 0, "can_add": False, "state": "missing_cloze", "reason": "missing_cloze", "duplicate_note_ids": []}], "stats": {}})}],
  "result": [{"index": 0, "canAdd": False, "state": "missingCloze", "reason": "missing_cloze", "duplicateNoteIds": []}]},
 {"name": "upsert sends match and on_match; an update comes back as updated",
  "call": m("notes.upsert", {**note, "matchField": "Front", "fieldRules": {"Back": "replaceIfEmpty", "*": "keep"}, "tagRule": "keep", "separator": " / "}),
  "exchanges": [{"request": post("/v1/notes:upsert", [{**wire, "match": {"field": "Front"},
                                                       "on_match": {"fields": {"Back": "replace_if_empty", "*": "keep"}, "tags": "keep", "separator": " / "}}]),
                 "response": ok({"created": [], "updated": [{"index": 0, "id": 9, "fields_changed": ["Back"], "tags_changed": False}], "failed": []})}],
  "result": {"action": "updated", "index": 0, "id": 9, "fieldsChanged": ["Back"], "tagsChanged": False, "cards": None}},
 {"name": "delete sends the note ids",
  "call": m("notes.delete", [1, 2]),
  "exchanges": [{"request": post("/v1/notes:delete", {"note_ids": [1, 2]}), "response": ok({"affected": 2, "stats": {}})}],
  "result": {"affected": 2}},
 {"name": "an id must be a positive integer", "call": m("cards.suspend", [0]), "exchanges": [], "error": {"kind": "argument"}},
 {"name": "a flag name the client doesn't know", "call": m("cards.setFlag", [1], "grene"), "exchanges": [], "error": {"kind": "argument"}},
 {"name": "media upload sends bytes as base64 and reports Anki's name",
  "call": m("media.upload", {"filename": "a.png", "data": {"$bytes": "AP8="}}),
  "exchanges": [{"request": post("/v1/media", [{"filename": "a.png", "data": "AP8="}]),
                 "response": ok({"created": [{"index": 0, "filename": "a-1.png", "requested_filename": "a.png", "renamed": True, "size": 2}], "failed": []})}],
  "result": {"index": 0, "filename": "a-1.png", "requestedFilename": "a.png", "renamed": True, "size": 2}},
 {"name": "sync that finishes at once",
  "call": m("collection.sync"),
  "exchanges": [{"request": post("/v1/collection:sync", None), "response": ok({"status": 0, "server_message": "", "stats": {}})}],
  "result": {"status": 0, "serverMessage": ""}},
 {"name": "sync that runs as a job is polled without submitting again",
  "call": m("collection.sync", {"pollIntervalMs": 1}),
  "exchanges": [
    {"request": post("/v1/collection:sync", None), "response": ok({"job_id": "abc", "status": "running", "stats": {}}, 202)},
    {"request": {"method": "GET", "path": "/v1/jobs/abc", "query": {}, "keyed": False}, "response": ok({"id": "abc", "kind": "sync", "status": "running", "result": None, "error": None, "stats": {}})},
    {"request": {"method": "GET", "path": "/v1/jobs/abc", "query": {}, "keyed": False},
     "response": ok({"id": "abc", "kind": "sync", "status": "done", "result": {"status": 1, "server_message": "done"}, "error": None, "stats": {}})}],
  "result": {"status": 1, "serverMessage": "done"}},
 {"name": "a failed sync job is a job error with the server's detail",
  "call": m("collection.sync", {"pollIntervalMs": 1}),
  "exchanges": [
    {"request": post("/v1/collection:sync", None), "response": ok({"job_id": "abc", "status": "queued", "stats": {}}, 202)},
    {"request": {"method": "GET", "path": "/v1/jobs/abc", "query": {}, "keyed": False}, "response": ok({"id": "abc", "kind": "sync", "status": "failed", "result": None, "error": "Sync failed", "stats": {}})}],
  "error": {"kind": "jobFailed", "detail": "Sync failed"}},
 {"name": "health in client names",
  "call": m("health"),
  "exchanges": [{"request": {"method": "GET", "path": "/v1/health", "query": {}, "keyed": False},
                 "response": ok({"ok": True, "server": "Tsunagi", "version": "0.5.1", "port": 7777, "versions": {"api": "v1", "addon": "0.5.1", "anki": "26.09"},
                                 "collection": {"state": "ready", "profile": "User 1"},
                                 "caller": {"name": "Yomine", "role": "Everything", "enabled": True, "key": "valid", "this_computer": False, "host": "pc"}})}],
  "result": {"server": "Tsunagi", "port": 7777, "versions": {"api": "v1", "addon": "0.5.1", "anki": "26.09"},
             "collection": {"state": "ready", "profile": "User 1"},
             "caller": {"name": "Yomine", "role": "Everything", "enabled": True, "key": "valid", "thisComputer": False, "host": "pc"}}},
]
verbs = [
 ("suspend", [[1]], {}), ("unsuspend", [[1]], {}), ("bury", [[1]], {}), ("unbury", [[1]], {}),
 ("forget", [[1], {"resetCounts": True}], {"restore_position": False, "reset_counts": True}),
 ("setDueDate", [[1], "3-7"], {"days": "3-7"}),
 ("changeDeck", [[1], {"id": 7}], {"deck_id": 7}),
 ("changeDeck", [[1], "Japanese::Done"], {"deck_name": "Japanese::Done"}),
 ("reposition", [[1]], {"starting_from": 0, "step_size": 1, "randomize": False, "shift_existing": False}),
 ("setFlag", [[1, 2], "purple"], {"flag": 7}),
]
paths = {"setDueDate": "set-due-date", "changeDeck": "change-deck", "setFlag": "set-flag"}
for verb, args, extra in verbs:
    cases.append({"name": f"cards.{verb} sends the card ids" + (f" and {', '.join(extra)}" if extra else ""),
                  "call": m(f"cards.{verb}", *args),
                  "exchanges": [{"request": post(f"/v1/cards:{paths.get(verb, verb)}", {"card_ids": args[0], **extra}), "response": ok({"affected": 1, "stats": {}})}],
                  "result": {"affected": 1}})
cases.append({"name": "cards.answer sends each rating as its ease",
              "call": m("cards.answer", [{"cardId": 1, "rating": "hard"}, {"cardId": 2, "rating": "easy"}]),
              "exchanges": [{"request": post("/v1/cards:answer", {"answers": [{"card_id": 1, "ease": 2}, {"card_id": 2, "ease": 4}]}), "response": ok({"affected": 2, "stats": {}})}],
              "result": {"affected": 2}})
