"""Export validated query rows, retaining Pydantic for richer export behavior."""
from typing import Any

from pydantic import BaseModel

_DEFAULT = object()
_MODEL_DICT = BaseModel.dict
_MODEL_ITER = BaseModel._iter
_MODEL_GET_VALUE = BaseModel._get_value.__func__
_MODEL_CALCULATE_KEYS = BaseModel._calculate_keys


class _NeedsPydantic(Exception):
    pass


def _model_values(row: BaseModel, include: Any = None) -> dict:
    # Custom exporters and schema-level field masks must keep Pydantic's rules.
    if (getattr(row.dict, "__func__", None) is not _MODEL_DICT
            or getattr(row._iter, "__func__", None) is not _MODEL_ITER
            or getattr(row._get_value, "__func__", None) is not _MODEL_GET_VALUE
            or getattr(row._calculate_keys, "__func__", None) is not _MODEL_CALCULATE_KEYS
            or row.__custom_root_type__ or "__root__" in row.__dict__
            or row.__include_fields__ or row.__exclude_fields__):
        raise _NeedsPydantic
    return _include_items(row._iter(to_dict=False), include)


def _include_items(items: Any, include: Any) -> dict:
    if include is not None and type(include) not in (set, dict):
        raise _NeedsPydantic
    if type(include) is dict and any(mask is not True for mask in include.values()):
        return {key: _selected_values(value, include[key]) for key, value in items
                if key in include}
    # Full rows and flat masks do not need per-value mask processing.
    return {key: _plain_values(value) for key, value in items
            if include is None or key in include}


def _selected_values(value: Any, include: Any) -> Any:
    if include is True or include is None:
        return _plain_values(value)
    if isinstance(value, BaseModel):
        return _model_values(value, include)
    if type(value) is dict and all(type(key) is str for key in value):
        return _include_items(value.items(), include)
    if type(value) is list and type(include) is dict and set(include) == {"__all__"}:
        mask = include["__all__"]
        # Empty __all__ masks have special sequence semantics in Pydantic.
        if mask:
            return [_selected_values(item, mask) for item in value]
    raise _NeedsPydantic


def _simple_mask(mask: Any) -> bool:
    # Only the nonempty, string-keyed masks generated by field selections.
    # Other Pydantic masks can merge or normalize keys before visiting values.
    if type(mask) is set:
        return bool(mask) and all(type(key) is str for key in mask)
    return type(mask) is dict and bool(mask) and all(
        type(key) is str and (value is True or _simple_mask(value))
        for key, value in mask.items()
    )


def _plain_values(value: Any) -> Any:
    kind = type(value)
    if value is None or kind in (str, int, float, bool):
        return value
    if kind is list:
        return [_plain_values(item) for item in value]
    if kind is dict:
        if any(type(key) is not str for key in value):
            raise _NeedsPydantic
        # Keep all keys here, including _sa: filters/projections run before the
        # HTTP encoder applies its exclusions.
        return {key: _plain_values(item) for key, item in value.items()}
    if isinstance(value, BaseModel):
        return _model_values(value)
    raise _NeedsPydantic


def model_row_dict(row: BaseModel, include: Any = _DEFAULT) -> dict:
    """Match row.dict() for ordinary JSON rows and common field selections.

    Validation has already run. Every call reads this row again and creates
    fresh containers; no row values or model metadata are cached.
    """
    mask = None if include is _DEFAULT else include
    try:
        if mask is not None and type(mask) is not set and not _simple_mask(mask):
            raise _NeedsPydantic
        return _model_values(row, mask)
    except _NeedsPydantic:
        # Fall back for the whole row so nested aliases, roots, custom methods,
        # non-JSON values and include/exclude rules retain their interactions.
        return row.dict() if include is _DEFAULT else row.dict(include=include)
