export { Tsunagi, SyncOperation } from "./client.js";
export type { SyncOptions, CreateOptions } from "./client.js";
export { AccessSnapshot } from "./access.js";
export type { AccessDecision, AccessBatch } from "./access.js";
export type { AccessTarget } from "./access-target.js";
export type { Subscription } from "./subscription.js";
export type { Query, Page, PageOptions, Operator, QueryResource, SortOf, WatchResource, WatchRow, WatchKey } from "./query.js";
export type { Change, WatchHandlers } from "./watch.js";
export type * from "./types.js";
export * from "./errors.js";
