"""Opt-in pytest action inventory; execution evidence, not a parity certificate.

Run from the repository root:
    python -m pytest -p tools.shim_coverage --shim-coverage=/tmp/shim-coverage.json
    python -m tools.shim_coverage /tmp/shim-coverage.json docs/archive/shim_coverage_matrix.md

The report records parameter names/types, never field contents or credentials.
Dispatcher-only actions (multi/requestPermission) need separate protocol tests.
"""

import functools
import json
from pathlib import Path
from threading import Lock

import pytest


def pytest_addoption(parser):
    parser.addoption("--shim-coverage", help="Write shim action execution evidence to JSON")


class Recorder:
    def __init__(self, registry):
        self.registry = registry
        self.nodeid = "<outside test>"
        self.lock = Lock()
        self.calls = {}
        self.outcomes = {}

    def record(self, action, params, outcome):
        shape = tuple(sorted(
            (str(key), type(value).__name__) for key, value in (params or {}).items()
        )) if isinstance(params, dict) or params is None else (("<params>", type(params).__name__),)
        with self.lock:
            key = (action, self.nodeid, shape, outcome)
            self.calls[key] = self.calls.get(key, 0) + 1

    @pytest.hookimpl(hookwrapper=True)
    def pytest_runtest_protocol(self, item, nextitem):
        self.nodeid = item.nodeid
        yield
        self.nodeid = "<outside test>"

    def pytest_runtest_logreport(self, report):
        self.outcomes.setdefault(report.nodeid, {})[report.when] = report.outcome

    def report(self):
        actions = {}
        for action in sorted(self.registry.list_actions()):
            handler, model = self.registry._handlers[action]
            fields = {} if model is None else {
                name: {"required": field.required, "alias": field.alias}
                for name, field in model.__fields__.items()
            }
            calls = [
                {"test": nodeid, "parameters": dict(shape), "outcome": outcome, "count": count}
                for (name, nodeid, shape, outcome), count in sorted(self.calls.items())
                if name == action
            ]
            actions[action] = {
                "handler": handler.__module__ + "." + handler.__name__,
                "declared_parameters": fields,
                "observed": bool(calls),
                "calls": calls,
            }
        return {
            "schema_version": 1,
            "meaning": "Handler execution only; mocks, assertions, upstream equality and UI behavior are not verified.",
            "dispatcher_only": ["multi", "requestPermission"],
            "actions": actions,
            "test_outcomes": self.outcomes,
        }


def pytest_collection_finish(session):
    if not session.config.getoption("--shim-coverage"):
        return
    if hasattr(session.config, "workerinput") or session.config.getoption("numprocesses", default=0):
        raise pytest.UsageError("--shim-coverage requires a single pytest process")
    # Import after collection: conftest installs Anki's test environment first.
    from tsunagi.http.compat.registry import registry

    recorder = Recorder(registry)
    original = registry.handle

    @functools.wraps(original)
    def handle(action_name, params=None):
        try:
            result = original(action_name, params)
        except Exception as exc:
            recorder.record(action_name, params, "raised:" + type(exc).__name__)
            raise
        recorder.record(action_name, params, "returned")
        return result

    registry.handle = handle
    session.config.pluginmanager.register(recorder, "shim-coverage-recorder")

    def finish():
        registry.handle = original
        destination = Path(session.config.getoption("--shim-coverage"))
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(json.dumps(recorder.report(), indent=2) + "\n", encoding="utf-8")

    session.config.add_cleanup(finish)


def render_markdown(report):
    actions = report["actions"]
    observed = sum(action["observed"] for action in actions.values())
    lines = [
        "# Shim test execution matrix", "",
        "Generated by `tools/shim_coverage.py`. See [behavioral coverage plan](shim_behavioral_coverage.md).", "",
        f"{observed}/{len(actions)} registered handlers were observed in this run. "
        "The two dispatcher-only actions are listed separately below.", "",
        "A return is not proof of success or upstream parity: it can be false, an embedded error, "
        "or a mocked result. Counts include fixture calls. Test files link to the assertions; "
        "the JSON report retains individual test IDs, outcomes, and parameter shapes. "
        "Optional parameters listed here were never explicitly supplied; other parameters may "
        "still lack default, null, false, empty, nested, or invalid-value coverage.", "",
        "| Action | Returned calls | Raised calls | Test files | Optional parameters never supplied |",
        "| --- | ---: | ---: | --- | --- |",
    ]
    for name, action in sorted(actions.items()):
        calls = action["calls"]
        returned = sum(c["count"] for c in calls if c["outcome"] == "returned")
        raised = sum(c["count"] for c in calls if c["outcome"].startswith("raised:"))
        files = sorted({c["test"].split("::")[0] for c in calls})
        links = ", ".join(f"[{Path(p).name}](../{p})" for p in files) or "**Not observed**"
        missing = [
            f"`{parameter}`" for parameter, field in action["declared_parameters"].items()
            if not field["required"] and not any(field["alias"] in c["parameters"] for c in calls)
        ]
        lines.append(f"| `{name}` | {returned} | {raised} | {links} | {', '.join(missing) or '—'} |")
    lines += [
        "", "## Dispatcher-only actions", "",
        "These bypass the handler registry and are not measured by this recorder.", "",
        "| Action | Existing protocol tests |", "| --- | --- |",
        "| `multi` | [test_compat_dispatcher.py](../tests/test_compat_dispatcher.py), "
        "[test_parity_history.py](../tests/test_parity_history.py) |",
        "| `requestPermission` | [test_request_permission.py](../tests/test_request_permission.py), "
        "[test_compat_dispatcher.py](../tests/test_compat_dispatcher.py) |", "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Render shim execution evidence as Markdown")
    parser.add_argument("report", type=Path)
    parser.add_argument("destination", type=Path)
    arguments = parser.parse_args()
    arguments.destination.write_text(
        render_markdown(json.loads(arguments.report.read_text(encoding="utf-8"))), encoding="utf-8",
    )
